# Generated by Django 5.1.4 on 2025-01-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(verbose_name='Date Rated'),
        ),
    ]
